import { ProductProps } from "@/@types/product";
import { SectionImage } from "@/components/Home";
import { SectionProducts } from "@/components/Home/SectionProducts";
import { Box } from "@chakra-ui/react";
import axios from "axios";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
interface HomeProps {
  products: ProductProps[];
}

const Home: NextPage<HomeProps> = ({ products }) => {
  return (
    <Box>
      <Head>
        <title>Candle App | Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionImage />
      <SectionProducts products={products} />
    </Box>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const response = await axios.get("http://localhost:3333/products");
  const products = response.data;

  return {
    props: {
      products: products,
    },
  };
};
