import { ProductProps } from "@/@types/product";
import {
  SectionImage,
  SectionAbout,
  SectionProducts,
  SectionTestimonials,
  SectionMostSold,
} from "@/components/Home";
import { Box } from "@chakra-ui/react";
import axios from "axios";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
interface HomeProps {
  products: ProductProps[];
  mostSoldProducts: ProductProps[];
}

const Home: NextPage<HomeProps> = ({ products, mostSoldProducts }) => {
  return (
    <Box>
      <Head>
        <title>Candle App | Início</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SectionImage />
      <SectionProducts products={products} />
      <SectionAbout />
      <SectionTestimonials />
      <SectionMostSold products={mostSoldProducts} />
    </Box>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const response = await axios.get<ProductProps[]>(
    "http://localhost:3333/products"
  );
  const products = response.data;
  const mostSoldProducts = products.slice(0, 4);

  return {
    props: {
      products: products,
      mostSoldProducts,
    },
  };
};
