import { ProductProps } from "@/@types/product";
import {
  SectionImage,
  SectionAbout,
  SectionProducts,
  SectionTestimonials,
  SectionMostSold,
} from "@/components/Landing";
import { Section } from "@/layout";
import { api } from "@/services";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

interface LandingProps {
  products: ProductProps[];
  mostSoldProducts: ProductProps[];
}

const Landing: NextPage<LandingProps> = ({ products, mostSoldProducts }) => {
  return (
    <>
      <Head>
        <title>Candle App | Início</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Section>
        <SectionImage />
        <SectionProducts products={products} />
        <SectionAbout />
        <SectionTestimonials />
        <SectionMostSold products={mostSoldProducts} />
      </Section>
    </>
  );
};

export default Landing;

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await api.get<ProductProps[]>("/products");
  const products = response.data;
  const mostSoldProducts = products.slice(0, 4);

  return {
    props: {
      products: products,
      mostSoldProducts,
    },
  };
};
